# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c365e4daa78c2616b7ecb9a4524cba2e36963342d066c2ac0e2ef73cdcce953fd33968f9249657a7afcfdd69d9a49cce3d6db1e31c3a2b3a7c89cff10faaa887

test:
  secret_key_base: 0d69d1c4e4da375f49f5bc2d93ba992af12d4681fadc84775e5912c5d8436ac78ec9d363a3aca63d443bbeb08aab0fb91d8c7aa7536f23e703db690966c95c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
