# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba53cfacfb73c30a7536f08d09ac32766ec079e6b35c4f8f7c02adb0e9ba989e9dbff5f032ada42a1f4fc70aaff128f7a24e4ad156bf281692ef4808f37a5494

test:
  secret_key_base: 746de04b7724ddd0647603560cfbda55f15eac278832ced6b89ecac9ca70c7b6a80ac4fef0a86751424abd39590eb0672a9720cb12f297ba14b7b29ec28a2560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
